

name: CI

on:
  pull_request:
  push:
    branches:
      - main
      

jobs:
  tests:
    name: Test ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install package and test requirements
        run: python -m pip install .[test]
      
